# Generated by Django 3.2 on 2022-01-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details_table',
            name='date_time',
            field=models.DateTimeField(unique=True),
        ),
    ]
